// vue-movie-app/src/components/MovieCard.vue
<script setup>

// 아버지인 MovieList에서 movie Prop를 상속받음
const props = defineProps(['movie']);

const imgSrc = `https://image.tmdb.org/t/p/w500/${props.movie.poster_path}`
</script>

<template>
  <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow m-3 dark:bg-gray-800 dark:border-gray-700">
        <a href="#">
            <img class="rounded-t-lg" :src="imgSrc" alt="" />
        </a>
        <div class="p-5">
            <a href="#">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ movie.title }}</h5>
            </a>
            <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{ movie.overview? movie.overview : '내용 없음'  }}</p>
            
        </div>
    </div>
</template>

<style scoped>

</style>

// react-movie-app/src/components/MovieCard.jsx
export default function MovieCard({movie}) {

    const {title, overview, poster_path} = movie;

    const imgSrc = `https://image.tmdb.org/t/p/w500/${poster_path}`;

    return(
        <div className="max-w-sm bg-white border border-gray-200 rounded-lg shadow m-3 dark:bg-gray-800 dark:border-gray-700">
                <a href="#">
                    <img className="rounded-t-lg" 
                    src={imgSrc} alt="" />
                </a>
                <div className="p-5">
                    <a href="#">
                        <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{title}</h5>
                    </a>
                    <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">{overview ? overview : '설명 없음'}</p>
                </div>
            </div>

    )
}
